---
title: "Flight Incidents FiveThirtyEight"
author: "Bill Lang"
date: "11/30/2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fivethirtyeight)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(scales)
tinytex::install_tinytex()
```

```{r}

airline_safety1 <- airline_safety %>% 
  select(airline, fatalities_85_99, fatalities_00_14, avail_seat_km_per_week) %>% 
  mutate(km_trillion = avail_seat_km_per_week*(52)*(14),
           fatalities_85_99a = fatalities_85_99/km_trillion*1000000000000,
           fatalities_00_14a = fatalities_00_14/km_trillion*1000000000000)

airline_safety1 %>% 
  ggplot(mapping = aes(x = fatalities_85_99a, y = fatalities_00_14a))+
  geom_point(size = 2, alpha = 0.5)+
  geom_smooth(method = "lm", se = FALSE, color = 'red', size = 1.3)+ 
  scale_y_continuous(breaks = c(0,250,500,750,1000,1250,1500),
                     labels = c(0,250,500,750,"1,000", "1,250","1,500"), 
                     limits = c(0, 1500))+
  scale_x_continuous(breaks = c(0,250,500,750,1000,1250,1500),
                     labels = c(0,250,500,750,"1,000", "1,250","1,500"), 
                     limits = c(0, 1500))+
  geom_hline(yintercept = 0,color="black") + 
  geom_vline(xintercept = 0,color="black") + 
  geom_text(x = 40, y = 1400, label = "Kenya \nAirways", size = 3.6, hjust = 0, color = 'dim gray')+
  geom_text(x = 65, y = 750, label = "Malaysia\n Airlines", size = 3.6, hjust = 0, color = 'dim gray')+
  geom_text(x = 940, y = 420, label = "China \nAirlines", size = 3.6, hjust = 0, color = 'dim gray')+
  geom_text(x = 950, y = 200, label = "Pakistan \nInternational", size = 3.6, hjust = 0, color = 'dim gray')+
  geom_text(x = 1150, y = 50, label = "Avianca", size = 3.6, hjust = 0, color = 'dim gray')+
  labs(title = "Fatalities by Airlines Are Highly Unpredictable", 
       subtitle = "Fatalitis adjusted for seats available and distance traveled \n(deaths per 1 trillion seat kilometers)", 
       x = "1985-99", 
       y = "2000-14")+
  theme(
        axis.ticks = element_blank(),
        panel.grid.major = element_line(color = 'light gray'),   
        panel.background = element_blank(), 
        plot.title = element_text(hjust = 0, size = rel(1.5), face = "bold"),
        plot.subtitle = element_text(hjust = 0))+
   coord_equal(ratio = 1) 

```

[Link to the Five Thirty Eight article I used for this project.]
(https://fivethirtyeight.com/features/should-travelers-avoid-flying-airlines-that-have-had-crashes-in-the-past/)








